//------------------------------------------------------------------------------
//
//  Copyright (c) 2016 Glympse Inc. All rights reserved.
//
//------------------------------------------------------------------------------

@class GlyGroupInvite;
@class GlyTicket;
@class GlyConfig;
@class GlyPredefinedMessage;
@class GlyCardEvent;
@class GlyCardTicketBuilder;
@class GlyCardActivity;
@class GlyServerError;
@class GlyCardMemberState;
@class GlyTriggersManager;
@class GlyTimeConstraint;
@class GlyPlaceSearchResult;
@class GlyGroupAd;
@class GlyFavoritesManager;
@class GlyGlympseFactory;
@class GlyDataEvent;
@class GlyCustomerPickupManager;
@class GlyLinkedAccountsManager;
@class GlyUserTicket;
@class GlyDirections;
@class GlyCardObject;
@class GlyHandoffProvider;
@class GlyGlympseTools;
@class GlyPlaceSearchEngine;
@class GlyDefinedRoute;
@class GlyPoi;
@class GlyGlympseEvents;
@class GlyCoreHealthCheck;
@class GlyCardInvite;
@class GlyPickupHours;
@class GlyAddress;
@class GlyAction;
@class GlyPickupDay;
@class GlyHealthReport;
@protocol GlyXoAListener;
@class GlyChatManager;
@class GlyCardTicket;
@class GlyUser;
@class GlyCustomerPickup;
@class GlyCard;
@class GlyRoutePlanner;
@class GlyCardType;
@class GlyPlace;
@class GlyTrigger;
@class GlyGroupBranding;
@class GlyPoiBuilder;
@class GlyPoiManager;
@class GlyApiStatus;
@class GlyNetworkManager;
@class GlyPlaceSearchRequest;
@class GlyDataRow;
@class GlyChatMessage;
@class GlyCardMemberTicket;
@class GlyRoutingConfigProvider;
@class GlyCardMemberDescriptor;
@class GlyTravelMode;
@class GlyBatteryManager;
@class GlyConsentManager;
@class GlyImage;
@protocol GlyApiStatusListener;
@class GlyPickupArrivalDataBuilder;
@class GlyAppProfile;
@class GlyCardManager;
@class GlyHandoffManager;
@class GlyHistoryManager;
@class GlyLocationManager;
@class GlyGlympseConstants;
@class GlyPairingManager;
@class GlyInviteViewer;
@class GlyUserManager;
@class GlyGroup;
@class GlyPickupItem;
@class GlyTrack;
@class GlyInvite;
@class GlyChatRoom;
@class GlyTrackBuilder;
@class GlyPlaceSearchResults;
@class GlyApplicationsManager;
@class GlyInviteViewers;
@class GlyGroupManager;
@class GlyLinkedAccount;
@class GlyPickupArrivalData;
@class GlyDirectionsManager;
@class GlyGlympse;
@class GlyChronoTrigger;
@class GlyCardObjectInvite;
@class GlyEtaTrigger;
@class GlyApplication;
@class GlyCardMember;
@class GlyRemoteTrigger;
@class GlyDepartureTrigger;
@class GlyArrivalTrigger;
@class GlyGeoTrigger;
@class GlyGroupMember;
@class GlyCardObjectPoi;
@class GlyRemoteGeoTrigger;

#import "GlyGroupInvite.h"
#import "GlyTicket.h"
#import "GlyConfig.h"
#import "GlyPredefinedMessage.h"
#import "GlyCardEvent.h"
#import "GlyCardTicketBuilder.h"
#import "GlyCardActivity.h"
#import "GlyServerError.h"
#import "GlyCardMemberState.h"
#import "GlyTriggersManager.h"
#import "GlyTimeConstraint.h"
#import "GlyPlaceSearchResult.h"
#import "GlyGroupAd.h"
#import "GlyFavoritesManager.h"
#import "GlyGlympseFactory.h"
#import "GlyDataEvent.h"
#import "GlyCustomerPickupManager.h"
#import "GlyLinkedAccountsManager.h"
#import "GlyUserTicket.h"
#import "GlyDirections.h"
#import "GlyCardObject.h"
#import "GlyHandoffProvider.h"
#import "GlyGlympseTools.h"
#import "GlyPlaceSearchEngine.h"
#import "GlyDefinedRoute.h"
#import "GlyPoi.h"
#import "GlyGlympseEvents.h"
#import "GlyCoreHealthCheck.h"
#import "GlyCardInvite.h"
#import "GlyPickupHours.h"
#import "GlyAddress.h"
#import "GlyAction.h"
#import "GlyPickupDay.h"
#import "GlyHealthReport.h"
#import "GlyXoAListener.h"
#import "GlyChatManager.h"
#import "GlyCardTicket.h"
#import "GlyUser.h"
#import "GlyCustomerPickup.h"
#import "GlyCard.h"
#import "GlyRoutePlanner.h"
#import "GlyCardType.h"
#import "GlyPlace.h"
#import "GlyTrigger.h"
#import "GlyGroupBranding.h"
#import "GlyPoiBuilder.h"
#import "GlyPoiManager.h"
#import "GlyApiStatus.h"
#import "GlyNetworkManager.h"
#import "GlyPlaceSearchRequest.h"
#import "GlyDataRow.h"
#import "GlyChatMessage.h"
#import "GlyCardMemberTicket.h"
#import "GlyRoutingConfigProvider.h"
#import "GlyCardMemberDescriptor.h"
#import "GlyTravelMode.h"
#import "GlyBatteryManager.h"
#import "GlyConsentManager.h"
#import "GlyImage.h"
#import "GlyApiStatusListener.h"
#import "GlyPickupArrivalDataBuilder.h"
#import "GlyAppProfile.h"
#import "GlyCardManager.h"
#import "GlyHandoffManager.h"
#import "GlyHistoryManager.h"
#import "GlyLocationManager.h"
#import "GlyGlympseConstants.h"
#import "GlyPairingManager.h"
#import "GlyInviteViewer.h"
#import "GlyUserManager.h"
#import "GlyGroup.h"
#import "GlyPickupItem.h"
#import "GlyTrack.h"
#import "GlyInvite.h"
#import "GlyChatRoom.h"
#import "GlyTrackBuilder.h"
#import "GlyPlaceSearchResults.h"
#import "GlyApplicationsManager.h"
#import "GlyInviteViewers.h"
#import "GlyGroupManager.h"
#import "GlyLinkedAccount.h"
#import "GlyPickupArrivalData.h"
#import "GlyDirectionsManager.h"
#import "GlyGlympse.h"
#import "GlyChronoTrigger.h"
#import "GlyCardObjectInvite.h"
#import "GlyEtaTrigger.h"
#import "GlyApplication.h"
#import "GlyCardMember.h"
#import "GlyRemoteTrigger.h"
#import "GlyDepartureTrigger.h"
#import "GlyArrivalTrigger.h"
#import "GlyGeoTrigger.h"
#import "GlyGroupMember.h"
#import "GlyCardObjectPoi.h"
#import "GlyRemoteGeoTrigger.h"
