//------------------------------------------------------------------------------
//
//  Copyright (c) 2016 Glympse Inc. All rights reserved.
//
//------------------------------------------------------------------------------

@interface GlyGlympseConstants : NSObject
{
}

+ (int)SMS_SEND_MODE_DEFAULT;

+ (int)SMS_SEND_MODE_DEVICE;

+ (int)SMS_SEND_MODE_SERVER;

+ (int)SMS_SEND_AUTO;

+ (int)SMS_SEND_MANUAL;

+ (int)SMS_SEND_NOT_SUPPORTED;

+ (int)ETA_MODE_EXTERNAL;

+ (int)ETA_MODE_INTERNAL;

+ (int)INVITE_MODE_DEFAULT;

+ (int)INVITE_MODE_PROMPT_BEFORE_VIEWING;

+ (int)INVITE_MODE_ACTIVATE_USER;

+ (int)USER_TRACKING_MODE_ACTIVE;

+ (int)USER_TRACKING_MODE_ALL;

+ (int)TICKET_STATE_NONE;

+ (int)TICKET_STATE_ADDING;

+ (int)TICKET_STATE_INVALID;

+ (int)TICKET_STATE_ACTIVE;

+ (int)TICKET_STATE_EXPIRING;

+ (int)TICKET_STATE_EXPIRED;

+ (int)TICKET_STATE_DELETING;

+ (int)TICKET_STATE_DELETED;

+ (int)TICKET_STATE_FAILED_TO_CREATE;

+ (int)TICKET_STATE_CANCELLED;

+ (int)TICKET_STATE_DECODING;

+ (int)TICKET_STATE_ACTIVATING;

+ (int)INVITE_ASPECT_UNKNOWN;

+ (int)INVITE_ASPECT_TICKET;

+ (int)INVITE_ASPECT_REQUEST;

+ (int)INVITE_ASPECT_CARD;

+ (int)INVITE_TYPE_UNKNOWN;

+ (int)INVITE_TYPE_ACCOUNT;

+ (int)INVITE_TYPE_EMAIL;

+ (int)INVITE_TYPE_SMS;

+ (int)INVITE_TYPE_TWITTER;

+ (int)INVITE_TYPE_FACEBOOK;

+ (int)INVITE_TYPE_LINK;

+ (int)INVITE_TYPE_GROUP;

+ (int)INVITE_TYPE_SHARE;

+ (int)INVITE_TYPE_CLIPBOARD;

+ (int)INVITE_TYPE_EVERNOTE;

+ (int)INVITE_TYPE_APP;

+ (int)INVITE_STATE_NONE;

+ (int)INVITE_STATE_SERVERSENDING;

+ (int)INVITE_STATE_CLIENTSENDING;

+ (int)INVITE_STATE_NEEDTOSEND;

+ (int)INVITE_STATE_SUCCEEDED;

+ (int)INVITE_STATE_DELETING;

+ (int)INVITE_STATE_DELETED;

+ (int)INVITE_STATE_FAILED_TO_CREATE;

+ (int)INVITE_STATE_FAILED_TO_SEND;

+ (int)INVITE_STATE_FAILED_TO_DELETE;

+ (int)IMAGE_STATE_NONE;

+ (int)IMAGE_STATE_LOADING;

+ (int)IMAGE_STATE_LOADED;

+ (int)IMAGE_STATE_FAILED;

+ (int)GROUP_STATE_NONE;

+ (int)GROUP_STATE_INVALID;

+ (int)GROUP_STATE_ADDING;

+ (int)GROUP_STATE_PENDING;

+ (int)GROUP_STATE_ACTIVE;

+ (int)GROUP_STATE_LEAVING;

+ (int)GROUP_STATE_LEFT;

+ (int)GROUP_STATE_FAILED_TO_CREATE;

+ (int)GROUP_STATE_FAILED_TO_JOIN;

+ (int)GROUP_STATE_FAILED_TO_LEAVE;

+ (int)EXPIRE_ON_ARRIVAL_NONE;

+ (int)EXPIRE_ON_ARRIVAL_NOTIFY;

+ (int)EXPIRE_ON_ARRIVAL_AUTO;

+ (int)DELETE_AFTER_COMPLETE_OFF;

+ (int)DELETE_AFTER_COMPLETE_IMMEDIATE;

+ (int)DELETE_AFTER_COMPLETE_SCHEDULED;

+ (int)GROUP_NAME_CORRECT;

+ (int)GROUP_NAME_TOO_SHORT;

+ (int)GROUP_NAME_INVALID_CHARACTER;

+ (int)GROUP_NAME_JUST_DIGITS;

+ (int)DURATION_NO_CHANGE;

+ (long long int)HISTORY_LOOKBACK_DEFAULT;

+ (long long int)CONTEXT_KEY_MIN;

+ (long long int)CONTEXT_KEY_MAX;

+ (int)TICKET_FIELD_INVITES;

+ (int)TICKET_FIELD_DURATION;

+ (int)TICKET_FIELD_MESSAGE;

+ (int)TICKET_FIELD_DESTINATION;

+ (int)HANDOFF_ACTION_SEND;

+ (int)TRAVEL_MODE_DEFAULT;

+ (int)TRAVEL_MODE_DRIVE;

+ (int)TRAVEL_MODE_CYCLE;

+ (int)TRAVEL_MODE_WALK;

+ (int)TRAVEL_MODE_AIRLINE;

+ (int)TRAVEL_MODE_TRANSIT;

+ (int)ETA_QUERY_MODE_ALWAYS;

+ (int)ETA_QUERY_MODE_WATCHED;

+ (NSString*)TICKET_VISIBILITY_LOCATION_VISIBLE;

+ (NSString*)TICKET_VISIBILITY_LOCATION_CLOAKED;

+ (NSString*)TICKET_VISIBILITY_LOCATION_HIDDEN;

+ (NSString*)TICKET_VISIBILITY_KEY_LOCATION;

+ (NSString*)TICKET_VISIBILITY_KEY_CONTEXT;

+ (NSString*)LINKED_ACCOUNT_TYPE_FACEBOOK;

+ (NSString*)LINKED_ACCOUNT_TYPE_TWITTER;

+ (NSString*)LINKED_ACCOUNT_TYPE_EVERNOTE;

+ (NSString*)LINKED_ACCOUNT_TYPE_GOOGLE;

+ (NSString*)LINKED_ACCOUNT_TYPE_PAIRING;

+ (NSString*)LINKED_ACCOUNT_TYPE_PHONE;

+ (NSString*)LINKED_ACCOUNT_TYPE_EMAIL;

+ (NSString*)LINKED_ACCOUNT_TYPE_VERIZON;

+ (NSString*)LINKED_ACCOUNT_PROPERTY_INVITE_CLIENT_SEND;

+ (int)LINKED_ACCOUNT_STATE_NONE;

+ (int)LINKED_ACCOUNT_STATE_LINKING;

+ (int)LINKED_ACCOUNT_STATE_LINKED;

+ (int)LINKED_ACCOUNT_STATE_FAILED_TO_LINK;

+ (int)LINKED_ACCOUNT_STATE_UNLINKING;

+ (int)LINKED_ACCOUNT_STATE_UNLINKED;

+ (int)LINKED_ACCOUNT_STATE_FAILED_TO_UNLINK;

+ (int)LINKED_ACCOUNT_STATE_REFRESHING;

+ (int)LINKED_ACCOUNT_STATUS_NONE;

+ (int)LINKED_ACCOUNT_STATUS_OK;

+ (int)LINKED_ACCOUNT_STATUS_REFRESH_NEEDED;

+ (int)LINKED_ACCOUNT_LOGIN_NONE;

+ (int)LINKED_ACCOUNT_LOGIN_ENABLED;

+ (int)LINKED_ACCOUNT_LOGIN_DISABLED;

+ (int)SERVER_ERROR_UNKNOWN;

+ (int)SERVER_ERROR_FORMAT;

+ (int)SERVER_ERROR_ACCESS_DENIED;

+ (int)SERVER_ERROR_LINK_FAILED;

+ (int)SERVER_ERROR_LINK_MISMATCH;

+ (int)SERVER_ERROR_EXISTING_LINK;

+ (int)SERVER_ERROR_NOT_LINKED;

+ (int)SERVER_ERROR_INVALID_TOKEN;

+ (int)SERVER_ERROR_DISABLED;

+ (int)SERVER_ERROR_PASSWORD_REQUIRED;

+ (int)EXPIRATION_MODE_SYNCHRONIZED;

+ (int)EXPIRATION_MODE_DETACHED;

+ (int)TRACK_SOURCE_UNKNOWN;

+ (int)TRACK_SOURCE_GOOGLE_DIRECTIONS;

+ (int)TRACK_SOURCE_INFLIGHT;

+ (int)TRACK_SOURCE_HERE_DIRECTIONS;

+ (int)TRACK_SOURCE_GLYMPSE_DIRECTIONS;

+ (int)PLACE_SOURCE_GLYMPSE;

+ (int)PLACE_SOURCE_HERE;

+ (int)DIRECTIONS_STATE_UNKNOWN;

+ (int)DIRECTIONS_STATE_FETCHING;

+ (int)DIRECTIONS_STATE_SUCCESS;

+ (int)DIRECTIONS_STATE_FAILED;

+ (int)TRIGGER_TYPE_GEO;

+ (int)TRIGGER_TYPE_CHRONO;

+ (int)TRIGGER_TYPE_ETA;

+ (int)TRIGGER_TYPE_ARRIVAL;

+ (int)TRIGGER_TYPE_DEPARTURE;

+ (int)TRIGGER_TYPE_REMOTE_GEO_CIRCLE;

+ (int)TRIGGER_TYPE_REMOTE_ETA;

+ (NSString*)TRIGGER_REMOTE_GEO_CIRCLE_KEY;

+ (NSString*)TRIGGER_REMOTE_ETA_KEY;

+ (int)NETWORK_RESPONSE_CODE_ANY;

+ (int)NETWORK_RESPONSE_CODE_ANY_VALID;

+ (int)NETWORK_RESPONSE_CODE_2XX;

+ (int)NETWORK_RESPONSE_BODY_ANY;

+ (int)NETWORK_RESPONSE_BODY_NOT_EMPTY;

+ (int)NETWORK_RESPONSE_BODY_VALID_JSON;

+ (int)CARD_TICKET_REPLY_INACTIVE;

+ (int)CARD_TICKET_REPLY_NONE;

+ (int)CARD_TICKET_REPLY_ACCEPT;

+ (int)CARD_TICKET_REPLY_DECLINE;

+ (int)CARD_TICKET_REPLY_ANY;

+ (NSString*)CARD_OBJECT_TYPE_POI;

+ (NSString*)CARD_OBJECT_TYPE_INVITE;

+ (NSString*)CARD_OBJECT_TYPE_UNKNOWN;

+ (int)CARD_STATE_NONE;

+ (int)CARD_STATE_CREATING;

+ (int)CARD_STATE_PREVIEW;

+ (int)CARD_STATE_JOINING;

+ (int)CARD_STATE_ACTIVE;

+ (int)CARD_STATE_LEAVING;

+ (int)CARD_STATE_FAILED_TO_CREATE;

+ (int)CARD_STATE_FAILED_TO_JOIN;

+ (NSString*)CARD_ID_PRIVATE_GROUP;

+ (NSString*)CONSENT_TYPE_SUBJECT;

+ (NSString*)CONSENT_TYPE_GUARDIAN;

+ (NSString*)USER_CONSENT_NONE;

+ (NSString*)USER_CONSENT_NO;

+ (NSString*)USER_CONSENT_YES;

+ (NSString*)USER_CONSENT_EXEMPT;

+ (NSString*)PRIVACY_POLICY_URL;

+ (NSString*)TERMS_AND_CONDITIONS_URL;

+ (NSString*)CUSTOMER_PICKUP_PHASE_NEW;

+ (NSString*)CUSTOMER_PICKUP_PHASE_READY;

+ (NSString*)CUSTOMER_PICKUP_PHASE_LIVE;

+ (NSString*)CUSTOMER_PICKUP_PHASE_ARRIVED;

+ (NSString*)CUSTOMER_PICKUP_PHASE_COMPLETED;

+ (NSString*)CUSTOMER_PICKUP_PHASE_HOLD;

+ (NSString*)CUSTOMER_PICKUP_PHASE_CANCELLED;

+ (NSString*)TAG_IMAGE_TYPE_LOGO;

+ (NSString*)TAG_IMAGE_TYPE_AVATAR;

+ (NSString*)TAG_IMAGE_TYPE_AD;

@end