//------------------------------------------------------------------------------
//
//  Copyright (c) 2016 Glympse Inc. All rights reserved.
//
//------------------------------------------------------------------------------

@interface GlyGlympseEvents : NSObject
{
}

+ (int)LISTENER_PLATFORM;

+ (int)LISTENER_INVITE;

+ (int)LISTENER_USER;

+ (int)LISTENER_TICKET;

+ (int)LISTENER_NETWORK;

+ (int)LISTENER_BATTERY;

+ (int)LISTENER_IMAGE;

+ (int)LISTENER_LOCATION;

+ (int)LISTENER_GROUPS;

+ (int)LISTENER_GROUP;

+ (int)LISTENER_CONFIG;

+ (int)LISTENER_HANDOFF;

+ (int)LISTENER_LINKED_ACCOUNTS;

+ (int)LISTENER_APPLICATIONS;

+ (int)LISTENER_TRIGGERS;

+ (int)LISTENER_PLACE_SEARCH;

+ (int)LISTENER_PAIRING;

+ (int)LISTENER_FAVORITES;

+ (int)LISTENER_DIRECTIONS;

+ (int)LISTENER_CONFIRMATION_CODE;

+ (int)LISTENER_CARDS;

+ (int)LISTENER_CARD;

+ (int)LISTENER_CARD_ACTIVITY;

+ (int)LISTENER_CARD_MEMBER;

+ (int)LISTENER_CARD_INVITE;

+ (int)LISTENER_POIS;

+ (int)LISTENER_INVITE_VIEWERS;

+ (int)LISTENER_CONSENT;

+ (int)LISTENER_CUSTOMER_PICKUPS;

+ (int)LISTENER_CHAT;

+ (int)LISTENER_ROUTE_PLANNER;

+ (int)PLATFORM_ACCOUNT_CREATED;

+ (int)PLATFORM_ACCOUNT_CREATE_FAILED;

+ (int)PLATFORM_LOGIN_SUCCEEDED;

+ (int)PLATFORM_LOGIN_FAILED;

+ (int)PLATFORM_SESSION_FAILED;

+ (int)PLATFORM_SYNCED_WITH_SERVER;

+ (int)PLATFORM_STARTED;

+ (int)PLATFORM_STOPPED;

+ (int)PLATFORM_LOCATION;

+ (int)PLATFORM_LOCATIONS_APPENDED;

+ (int)PLATFORM_DATA_APPENDED;

+ (int)PLATFORM_USER_ADDED;

+ (int)PLATFORM_USER_REMOVED;

+ (int)PLATFORM_USER_CHANGED;

+ (int)PLATFORM_USER_LIST_REORDERED;

+ (int)PLATFORM_TICKET_ADDED;

+ (int)PLATFORM_TICKET_REMOVED;

+ (int)PLATFORM_TICKET_CHANGED;

+ (int)PLATFORM_TICKET_LIST_REORDERED;

+ (int)PLATFORM_TICKET_ARRIVED;

+ (int)PLATFORM_INVITE_TICKET;

+ (int)PLATFORM_INVITE_REQUEST;

+ (int)PLATFORM_FIRST_LAUNCH;

+ (int)PLATFORM_RATE_LIMITED;

+ (int)PLATFORM_STATE_CHANGED;

+ (int)PLATFORM_CARD_INVITE;

+ (int)PLATFORM_CARD_REQUEST;

+ (int)PLATFORM_TICKET_SYNC_COMPLETED;

+ (int)PLATFORM_USER_LIST_CHANGED;

+ (int)PLATFORM_TICKET_LIST_CHANGED;

+ (int)INVITE_DECODED;

+ (int)INVITE_INVALID_CODE;

+ (int)USER_NICKNAME_CHANGED;

+ (int)USER_ACTIVE_TICKET_CHANGED;

+ (int)USER_TICKET_ADDED;

+ (int)USER_TICKET_REMOVED;

+ (int)USER_AVATAR_UPLOADED;

+ (int)USER_AVATAR_NOT_UPLOADED;

+ (int)USER_ACTIVE_TICKET_RESIGNING;

+ (int)USER_CHANGED;

+ (int)TICKET_CREATED;

+ (int)TICKET_EXPIRED;

+ (int)TICKET_FIRST_VIEWED;

+ (int)TICKET_VISIBILITY_CHANGED;

+ (int)TICKET_DURATION_CHANGED;

+ (int)TICKET_MESSAGE_CHANGED;

+ (int)TICKET_DESTINATION_CHANGED;

+ (int)TICKET_TRACK_CHANGED;

+ (int)TICKET_ETA_CHANGED;

+ (int)TICKET_ROUTE_CHANGED;

+ (int)TICKET_TRAVEL_MODE_CHANGED;

+ (int)TICKET_INVALID_CODE;

+ (int)TICKET_INVITE_CREATED;

+ (int)TICKET_INVITE_SENT;

+ (int)TICKET_INVITE_UPDATED;

+ (int)TICKET_INVITE_REMOVED;

+ (int)TICKET_INVITE_FAILED;

+ (int)TICKET_REQUEST_CREATED;

+ (int)TICKET_REQUEST_SENT;

+ (int)TICKET_REQUEST_FAILED;

+ (int)TICKET_FAILED;

+ (int)TICKET_ARRIVED;

+ (int)TICKET_DATA_APPENDED;

+ (int)TICKET_DATA_CLEARED;

+ (int)TICKET_TRANSFERRED;

+ (int)TICKET_NOT_TRANSFERRED;

+ (int)TICKET_COMPLETED;

+ (int)TICKET_INVITE_CHANGED;

+ (int)TICKET_CHANGED;

+ (int)NETWORK_START_FAILING;

+ (int)NETWORK_RECOVERED;

+ (int)NETWORK_WILL_SEND_REQUEST;

+ (int)NETWORK_IS_PREPARING_REQUEST;

+ (int)NETWORK_IS_SENDING_REQUEST;

+ (int)NETWORK_POST_RATE_CALCULATED;

+ (int)NETWORK_RESPONSE_RECEIVED;

+ (int)NETWORK_CLOCKS_SYNCED;

+ (int)NETWORK_PUSH_AVAILABILITY_CHANGED;

+ (int)BATTERY_STATE_CHANGED;

+ (int)LOCATION_STATE_CHANGED;

+ (int)LOCATION_ACCURACY_AUTH_CHANGED;

+ (int)LOCATION_REGION_ENTERED;

+ (int)LOCATION_REGION_LEFT;

+ (int)LOCATION_PROFILE_CHANGED;

+ (int)LOCATION_PROVIDER_STOPPED;

+ (int)IMAGE_CHANGED;

+ (int)GROUPS_INVITE;

+ (int)GROUPS_DECODED;

+ (int)GROUPS_GROUP_ADDED;

+ (int)GROUPS_GROUP_REMOVED;

+ (int)GROUPS_SYNCED_WITH_SERVER;

+ (int)GROUPS_PREMIUM_CREATED;

+ (int)GROUPS_PREMIUM_CREATE_FAILED;

+ (int)GROUPS_PREMIUM_BRANDING_UPDATED;

+ (int)GROUPS_PREMIUM_BRANDING_UPDATE_FAILED;

+ (int)GROUPS_PREMIUM_SYNCED;

+ (int)GROUPS_PREMIUM_SYNC_FAILED;

+ (int)GROUPS_PREMIUM_ROUTE_SAVED;

+ (int)GROUPS_PREMIUM_ROUTE_SAVE_FAILED;

+ (int)GROUPS_PREMIUM_RESERVED;

+ (int)GROUPS_PREMIUM_RESERVE_FAILED;

+ (int)GROUPS_PREMIUM_IMAGE_SAVED;

+ (int)GROUPS_PREMIUM_IMAGE_SAVE_FAILED;

+ (int)GROUPS_PREMIUM_ROUTE_DELETED;

+ (int)GROUPS_PREMIUM_ROUTE_DELETE_FAILED;

+ (int)GROUPS_PREMIUM_PASSWORD_UPDATED;

+ (int)GROUPS_PREMIUM_PASSWORD_UPDATE_FAILED;

+ (int)GROUP_INVALID_CODE;

+ (int)GROUP_INVITE_CREATED;

+ (int)GROUP_INVITE_SENT;

+ (int)GROUP_INVITE_FAILED;

+ (int)GROUP_MEMBER_ADDED;

+ (int)GROUP_MEMBER_REMOVED;

+ (int)GROUP_ORDER_CHANGED;

+ (int)GROUP_FIRST_VIEWED;

+ (int)GROUP_MEMBER_TICKET_CHANGED;

+ (int)GROUP_MEMBER_TICKET_RESIGNING;

+ (int)GROUP_FAILED;

+ (int)GROUP_NAME_CHANGED;

+ (int)GROUP_CREATED;

+ (int)GROUP_CREATE_FAILED;

+ (int)CONFIG_XOA_CHANGED;

+ (int)CONFIG_LOCATION_SHARING_CHANGED;

+ (int)CONFIG_TICKET_SENT_CHANGED;

+ (int)CONFIG_ACCOUNTS_LINKED_CHANGED;

+ (int)CONFIG_CHANGED;

+ (int)HANDOFF_PROVIDER_CONNECTED;

+ (int)HANDOFF_PROVIDER_AVAILABLE;

+ (int)HANDOFF_PROVIDER_DISCONNECTED;

+ (int)LISTENER_ID_MIN;

+ (int)LISTENER_ID_MAX;

+ (int)ACCOUNT_LINK_SUCCEEDED;

+ (int)ACCOUNT_LINK_FAILED;

+ (int)ACCOUNT_UNLINK_SUCCEEDED;

+ (int)ACCOUNT_UNLINK_FAILED;

+ (int)ACCOUNT_REFRESH_SUCCEEDED;

+ (int)ACCOUNT_REFRESH_FAILED;

+ (int)ACCOUNT_LIST_REFRESH_SUCCEEDED;

+ (int)ACCOUNT_LIST_REFRESH_FAILED;

+ (int)CONFIRMATION_CODE_SENT;

+ (int)CONFIRMATION_CODE_FAILED;

+ (int)APPLICATIONS_APP_ADDED;

+ (int)APPLICATIONS_APP_REMOVED;

+ (int)APPLICATIONS_APP_CHANGED;

+ (int)APPLICATIONS_APP_LAUNCHED;

+ (int)TRIGGERS_TRIGGER_ADDED;

+ (int)TRIGGERS_TRIGGER_REMOVED;

+ (int)TRIGGERS_TRIGGER_ACTIVATED;

+ (int)TRIGGERS_REMOTE_TRIGGERS_SYNCED;

+ (int)TRIGGERS_REMOTE_TRIGGERS_SYNC_FAILED;

+ (int)TRIGGERS_REMOTE_TRIGGER_CREATED;

+ (int)TRIGGERS_REMOTE_TRIGGER_CREATE_FAILED;

+ (int)TRIGGERS_REMOTE_TRIGGER_DELETED;

+ (int)TRIGGERS_REMOTE_TRIGGER_DELETE_FAILED;

+ (int)PAIRING_CODE_CLAIMED;

+ (int)PAIRING_CODE_FAILED;

+ (int)PAIRING_GET_CODE_SUCCEEDED;

+ (int)PAIRING_GET_CODE_FAILED;

+ (int)PLACE_SEARCH_COMPLETED;

+ (int)PLACE_SEARCH_FAILED;

+ (int)FAVORITES_CHANGED;

+ (int)DIRECTIONS_SUCCEEDED;

+ (int)DIRECTIONS_FAILED;

+ (int)DIRECTIONS_NOT_FOUND;

+ (int)DIRECTIONS_CHANGED;

+ (int)CARD_MANAGER_CARD_ADDED;

+ (int)CARD_MANAGER_CARD_REMOVED;

+ (int)CARD_MANAGER_SYNCED;

+ (int)CARD_MANAGER_SYNC_FAILED;

+ (int)CARD_MANAGER_CARD_TYPES_UPDATED;

+ (int)CARD_STATE_CHANGED;

+ (int)CARD_NAME_UPDATED;

+ (int)CARD_MEMBER_ADDED;

+ (int)CARD_MEMBER_REMOVED;

+ (int)CARD_INVITE_ADDED;

+ (int)CARD_INVITE_REMOVED;

+ (int)CARD_OBJECT_ADDED;

+ (int)CARD_OBJECT_REMOVED;

+ (int)CARD_OBJECT_UPDATED;

+ (int)CARD_OBJECT_REMOVAL_FAILED;

+ (int)CARD_MEMBER_DELETE_FAILED;

+ (int)CARD_REQUEST_FAILED;

+ (int)CARD_ACTIVITY_CHANGED;

+ (int)CARD_ACTIVITY_SYNCED;

+ (int)CARD_EVENT_CREATED;

+ (int)CARD_EVENT_CREATE_FAILED;

+ (int)CARD_MEMBER_STARTED_SHARING;

+ (int)CARD_MEMBER_STOPPED_SHARING;

+ (int)CARD_MEMBER_TICKET_DECODED;

+ (int)CARD_MEMBER_STARTED_REQUESTING;

+ (int)CARD_MEMBER_STOPPED_REQUESTING;

+ (int)CARD_MEMBER_REQUEST_DECODED;

+ (int)CARD_MEMBER_REQUEST_DECLINED;

+ (int)CARD_MEMBER_STATE_CHANGED;

+ (int)CARD_INVITE_CREATED;

+ (int)CARD_INVITE_SENT;

+ (int)CARD_INVITE_FAILED;

+ (int)POI_LIST_SYNCED;

+ (int)POI_ADDED;

+ (int)POI_UPDATED;

+ (int)POI_REMOVED;

+ (int)INVITE_VIEWERS_ADDED;

+ (int)INVITE_VIEWERS_REMOVED;

+ (int)INVITE_VIEWERS_CLEARED;

+ (int)CONSENT_REQUIRED;

+ (int)CONSENT_SUCCEEDED;

+ (int)CONSENT_FAILED;

+ (int)CONSENT_REVOKE_SUCCEEDED;

+ (int)CONSENT_REVOKE_FAILED;

+ (int)CONSENT_MANAGER_SYNCED;

+ (int)CONSENT_MANAGER_SYNC_FAILED;

+ (int)CUSTOMER_PICKUPS_SET_ETA_SUCCEEDED;

+ (int)CUSTOMER_PICKUPS_SET_ETA_FAILED;

+ (int)CUSTOMER_PICKUPS_SET_ARRIVED_SUCCEEDED;

+ (int)CUSTOMER_PICKUPS_SET_ARRIVED_FAILED;

+ (int)CUSTOMER_PICKUPS_ARRIVAL_DATA_SUCCEEDED;

+ (int)CUSTOMER_PICKUPS_ARRIVAL_DATA_FAILED;

+ (int)CUSTOMER_PICKUPS_PICKUP_UPDATED;

+ (int)CUSTOMER_PICKUPS_PICKUP_FIRST_SYNC;

+ (int)CUSTOMER_PICKUPS_PICKUP_CHAT_MESSAGES_CHANGED;

+ (int)CUSTOMER_PICKUPS_SET_HOLD_SUCCEEDED;

+ (int)CUSTOMER_PICKUPS_SET_HOLD_FAILED;

+ (int)CUSTOMER_PICKUPS_SET_FEEDBACK_SUCCEEDED;

+ (int)CUSTOMER_PICKUPS_SET_FEEDBACK_FAILED;

+ (int)CHAT_MESSAGE_SENT;

+ (int)CHAT_MESSAGE_SEND_FAILED;

+ (int)CHAT_MESSAGES_SYNCED;

+ (int)CHAT_MESSAGES_SYNC_FAILED;

+ (int)CHAT_MESSAGE_RECEIVED;

+ (int)CHAT_FETCH_PREDEFINED_MESSAGES;

+ (int)CHAT_FETCH_PREDEFINED_MESSAGES_FAILED;

+ (int)ROUTE_UPDATED;

@end