//------------------------------------------------------------------------------
//
//  Copyright (c) 2016 Glympse Inc. All rights reserved.
//
//------------------------------------------------------------------------------

@interface GlyCoreConstants : NSObject
{
}

+ (int)PRIMITIVE_TYPE_ARRAY;

+ (int)PRIMITIVE_TYPE_OBJECT;

+ (int)PRIMITIVE_TYPE_DOUBLE;

+ (int)PRIMITIVE_TYPE_LONG;

+ (int)PRIMITIVE_TYPE_BOOLEAN;

+ (int)PRIMITIVE_TYPE_STRING;

+ (int)PRIMITIVE_TYPE_NULL;

+ (int)LOCATION_STATE_NOT_DETERMINED;

+ (int)LOCATION_STATE_DENIED;

+ (int)LOCATION_STATE_ACQUIRED;

+ (int)LOCATION_STATE_ERROR;

+ (int)LOCATION_ACCURACY_AUTH_FULL;

+ (int)LOCATION_ACCURACY_AUTH_REDUCED;

+ (int)LOCATION_PERMISSION_UNKNOWN;

+ (int)LOCATION_PERMISSION_DISABLED;

+ (int)LOCATION_PERMISSION_WHILE_IN_USE;

+ (int)LOCATION_PERMISSION_ALWAYS;

+ (int)INFO;

+ (int)DUMP;

+ (int)NOTICE;

+ (int)WARNING;

+ (int)ERROR;

+ (int)CRITICAL;

+ (int)NONE;

+ (int)LOCATION_PROFILE_NOT_SET;

+ (int)LOCATION_PROFILE_NO_ACTIVE_BACKGROUND;

+ (int)LOCATION_PROFILE_NO_ACTIVE_FOREGROUND;

+ (int)LOCATION_PROFILE_ACTIVE_NOT_WATCHED;

+ (int)LOCATION_PROFILE_ACTIVE_IS_WATCHED;

+ (int)LOCATION_PROFILES_COUNT;

+ (int)LOCATION_SOURCE_NETWORK;

+ (int)LOCATION_SOURCE_GPS;

+ (int)LOCATION_SOURCE_PASSIVE;

+ (int)LOCATION_SOURCE_ALL;

+ (int)LOCATION_MODE_ENABLED;

+ (int)LOCATION_MODE_DISABLED;

+ (int)LOCATION_PRIORITY_HIGH_ACCURACY;

+ (int)LOCATION_PRIORITY_BALANCED_POWER_ACCURACY;

+ (int)LOCATION_PRIORITY_NO_POWER;

+ (int)GEOFENCE_TRANSITION_ENTER;

+ (int)GEOFENCE_TRANSITION_EXIT;

+ (int)ETA_TRANSITION_DROPS_BELOW;

+ (int)ETA_TRANSITION_RISES_ABOVE;

+ (int)PUSH_AVAILABILITY_UNKNOWN;

+ (int)PUSH_AVAILABILITY_UNAVAILABLE;

+ (int)PUSH_AVAILABILITY_AVAILABLE;

+ (int)PUSH_AVAILABILITY_DENIED;

+ (int)MOBILE_DATA_UNKNOWN;

+ (int)MOBILE_DATA_DISABLED;

+ (int)MOBILE_DATA_ENABLED;

+ (int)RESTRICT_BACKGROUND_DISABLED;

+ (int)RESTRICT_BACKGROUND_ENABLED;

+ (int)RESTRICT_BACKGROUND_WHITELISTED;

+ (int)DRAWABLE_SCALE_EXACT;

+ (int)DRAWABLE_SCALE_FIT_OR_SMALLER;

+ (int)DRAWABLE_SCALE_FIT;

+ (int)DRAWABLE_SCALE_FILL_OR_SMALLER;

+ (int)DRAWABLE_SCALE_FILL;

+ (int)DRAWABLE_COMPRESS_JPG;

+ (int)DRAWABLE_COMPRESS_PNG;

+ (int)ACTIVITY_UNKNOWN;

+ (int)ACTIVITY_IN_VEHICLE;

+ (int)ACTIVITY_ON_BICYCLE;

+ (int)ACTIVITY_ON_FOOT;

+ (int)ACTIVITY_STILL;

+ (int)ACTIVITY_TILTING;

+ (int)HTTP_METHOD_DEFAULT;

+ (int)HTTP_METHOD_GET;

+ (int)HTTP_METHOD_POST;

+ (int)HTTP_METHOD_PUT;

+ (int)HTTP_METHOD_DELETE;

@end